language: r
r:
  - oldrel
  - release
  - devel
cache: packages

r_packages:
  - testthat
  - rmarkdown
  - knitr
  - party
  - randomForest
  - randomForestSRC
  - mmpf

before_install:
 - cd pkg

notifications:
  email:
    on_success: change
    on_failure: change